[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aquamarine-dredge"
version = "76.0.0"
description = "Pure Python Zero-Dependency Autonomous Biophysics & Mathematical Core"
readme = "README.md"
authors = [{ name = "Soma Dutta" }]
dependencies = []

[project.scripts]
aquamarine-dredge = "dredge.cli:main"
